package server

import (
	"encoding/json"
	"log"
	"net/http"

	_ "go-tasker/docs" // docs is generated by Swag CLI, you have to import it.

	httpSwagger "github.com/swaggo/http-swagger/v2"
)

func (s *Server) RegisterRoutes() http.Handler {
	mux := http.NewServeMux()
	apiV1 := "/api/v1"

	mux.HandleFunc("/", s.HelloWorldHandler)

	AddListsHandlers(mux, s, apiV1)
	AddTasksHandlers(mux, s, apiV1)
	AddProjectsHandlers(mux, s, apiV1)
	AddSwaggerHandler(mux)

	return mux
}

func AddSwaggerHandler(mux *http.ServeMux) {
	mux.Handle("/swagger/", httpSwagger.Handler(
		httpSwagger.URL("http://localhost:8080/swagger/doc.json"), // The URL pointing to API definition
	))
}

func AddListsHandlers(mux *http.ServeMux, s *Server, apiVersion string) {
	mux.HandleFunc("GET "+apiVersion+"/lists", s.GetListsHandler)
	mux.HandleFunc("POST "+apiVersion+"/lists", s.PostListsHandler)
	mux.HandleFunc("PUT "+apiVersion+"/lists/{id}", s.PutListHandler)
	mux.HandleFunc("DELETE "+apiVersion+"/lists/{id}", s.DeleteListHandler)
}

func AddTasksHandlers(mux *http.ServeMux, s *Server, apiVersion string) {
	mux.HandleFunc("GET "+apiVersion+"/lists/{listID}/tasks", s.GetTasksHandler)
	mux.HandleFunc("POST "+apiVersion+"/lists/{listID}/tasks", s.PostTasksHandler)
	mux.HandleFunc("PUT "+apiVersion+"/lists/{listID}/tasks/{taskID}", s.PutTaskHandler)
	mux.HandleFunc("DELETE "+apiVersion+"/lists/{listID}/tasks/{taskID}", s.DeleteTaskHandler)
	mux.HandleFunc("PATCH "+apiVersion+"/lists/{listID}/tasks/{taskID}/done", s.PatchTaskDoneHandler)
	mux.HandleFunc("PATCH "+apiVersion+"/lists/{listID}/tasks/{taskID}/undone", s.PatchTaskUndoneHandler)
}

func AddProjectsHandlers(mux *http.ServeMux, s *Server, apiVersion string) {
	mux.HandleFunc("GET "+apiVersion+"/projects", s.GetProjectsHandler)
	mux.HandleFunc("POST "+apiVersion+"/projects", s.PostProjectsHandler)
	mux.HandleFunc("PUT "+apiVersion+"/projects/{id}", s.PutProjectHandler)
	mux.HandleFunc("DELETE "+apiVersion+"/projects/{id}", s.DeleteProjectHandler)
}

func (s *Server) HelloWorldHandler(w http.ResponseWriter, r *http.Request) {
	response := make(map[string]string)
	response["message"] = "Hello World"

	jsonResp, err := json.Marshal(response)
	if err != nil {
		log.Fatalf("error handling JSON marshal. Err: %v", err)
	}

	_, _ = w.Write(jsonResp)
}
